# <u> Use only those concepts which have been taught till now </u>

In [2]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [3]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [4]:
# Your code here
np.mean(random_integers[0:5,3:5])





201466.2

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [9]:
# Create the 10 points
points = np.random.randint(5,high=21, size=(10,2))
print("Points:")
print(points)

Points:
[[15 19]
 [14 20]
 [16 16]
 [20 19]
 [18 18]
 [19 18]
 [ 7 16]
 [11  8]
 [20 13]
 [ 7  9]]


In [10]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
euclidean_distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        x1, y1 = points[i]
        x2, y2 = points[j]
        euclidean_distances[i, j] = np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)

print("\nEuclidean Distances:")
print(euclidean_distances)




Euclidean Distances:
[[ 0.          1.41421356  3.16227766  5.          3.16227766  4.12310563
   8.54400375 11.70469991  7.81024968 12.80624847]
 [ 1.41421356  0.          4.47213595  6.08276253  4.47213595  5.38516481
   8.06225775 12.36931688  9.21954446 13.03840481]
 [ 3.16227766  4.47213595  0.          5.          2.82842712  3.60555128
   9.          9.43398113  5.         11.40175425]
 [ 5.          6.08276253  5.          0.          2.23606798  1.41421356
  13.34166406 14.2126704   6.         16.40121947]
 [ 3.16227766  4.47213595  2.82842712  2.23606798  0.          1.
  11.18033989 12.20655562  5.38516481 14.2126704 ]
 [ 4.12310563  5.38516481  3.60555128  1.41421356  1.          0.
  12.16552506 12.80624847  5.09901951 15.        ]
 [ 8.54400375  8.06225775  9.         13.34166406 11.18033989 12.16552506
   0.          8.94427191 13.34166406  7.        ]
 [11.70469991 12.36931688  9.43398113 14.2126704  12.20655562 12.80624847
   8.94427191  0.         10.29563014  4.1231

In [11]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
manhattan_distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        x1, y1 = points[i]
        x2, y2 = points[j]
        manhattan_distances[i, j] = abs(x1 - x2) + abs(y1 - y2)

print("\nManhattan Distances:")
print(manhattan_distances)



Manhattan Distances:
[[ 0.  2.  4.  5.  4.  5. 11. 15. 11. 18.]
 [ 2.  0.  6.  7.  6.  7. 11. 15. 13. 18.]
 [ 4.  6.  0.  7.  4.  5.  9. 13.  7. 16.]
 [ 5.  7.  7.  0.  3.  2. 16. 20.  6. 23.]
 [ 4.  6.  4.  3.  0.  1. 13. 17.  7. 20.]
 [ 5.  7.  5.  2.  1.  0. 14. 18.  6. 21.]
 [11. 11.  9. 16. 13. 14.  0. 12. 16.  7.]
 [15. 15. 13. 20. 17. 18. 12.  0. 14.  5.]
 [11. 13.  7.  6.  7.  6. 16. 14.  0. 17.]
 [18. 18. 16. 23. 20. 21.  7.  5. 17.  0.]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [12]:
# Your code here
min_euclidean_distance = np.inf
euclidean_closest_pair = None
for i in range(10):
    for j in range(10):
        if i != j and euclidean_distances[i, j] < min_euclidean_distance:
            min_euclidean_distance = euclidean_distances[i, j]
            euclidean_closest_pair = (i, j)

# Find the closest pairs (excluding self-pairs) based on Manhattan distance
min_manhattan_distance = np.inf
manhattan_closest_pair = None
for i in range(10):
    for j in range(10):
        if i != j and manhattan_distances[i, j] < min_manhattan_distance:
            min_manhattan_distance = manhattan_distances[i, j]
            manhattan_closest_pair = (i, j)

print("\nClosest Pair based on Euclidean Distance:", euclidean_closest_pair)
print("Minimum Euclidean Distance:", min_euclidean_distance)
print("\nClosest Pair based on Manhattan Distance:", manhattan_closest_pair)
print("Minimum Manhattan Distance:", min_manhattan_distance)





Closest Pair based on Euclidean Distance: (4, 5)
Minimum Euclidean Distance: 1.0

Closest Pair based on Manhattan Distance: (4, 5)
Minimum Manhattan Distance: 1.0


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [2]:
# Your code below ..
import numpy as np

# Generate random 10x10 matrix
#np.random.seed(42)  # Set seed for reproducibility
matrix = np.random.randint(1, 100, size=(10, 10))
print(matrix)

# Extract contiguous 3x3 blocks
blocks = []
for i in range(8):  # Iterate over rows
    for j in range(8):  # Iterate over columns
        block = matrix[i:i+3, j:j+3]  # Extract 3x3 block
        blocks.append(block)

# Print the extracted blocks
for i, block in enumerate(blocks):
    print(f"Block {i+1}:")
    print(block)
    print() 

[[60 41 29 15 45 65 89 71  9 88]
 [ 1  8 88 63 11 81  8 35 35 33]
 [ 5 41 28  7 73 72 12 34 33 48]
 [23 62 88 37 99 44 86 91 35 65]
 [99 47 78  3  1  5 90 14 27  9]
 [79 15 90 42 77 51 63 96 52 96]
 [ 4 94 23 15 43 29 36 13 32 71]
 [59 86 28 66 42 45 62 57  6 28]
 [28 44 84 30 62 75 92 89 62 97]
 [ 1 27 62 77  3 70 72 27  9 62]]
Block 1:
[[60 41 29]
 [ 1  8 88]
 [ 5 41 28]]

Block 2:
[[41 29 15]
 [ 8 88 63]
 [41 28  7]]

Block 3:
[[29 15 45]
 [88 63 11]
 [28  7 73]]

Block 4:
[[15 45 65]
 [63 11 81]
 [ 7 73 72]]

Block 5:
[[45 65 89]
 [11 81  8]
 [73 72 12]]

Block 6:
[[65 89 71]
 [81  8 35]
 [72 12 34]]

Block 7:
[[89 71  9]
 [ 8 35 35]
 [12 34 33]]

Block 8:
[[71  9 88]
 [35 35 33]
 [34 33 48]]

Block 9:
[[ 1  8 88]
 [ 5 41 28]
 [23 62 88]]

Block 10:
[[ 8 88 63]
 [41 28  7]
 [62 88 37]]

Block 11:
[[88 63 11]
 [28  7 73]
 [88 37 99]]

Block 12:
[[63 11 81]
 [ 7 73 72]
 [37 99 44]]

Block 13:
[[11 81  8]
 [73 72 12]
 [99 44 86]]

Block 14:
[[81  8 35]
 [72 12 34]
 [44 86 91]]

Block 

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [8]:
# Your function below
import numpy as np

def find_nearest_value(value, array):
    array = np.array(array)
    absolute_diff = np.abs(array - value)
   
    nearest_index = np.argmin(absolute_diff)
    
    nearest_value = array[nearest_index]
    return nearest_value

# Example usage
random_array = np.random.randint(10, 501, size=15)

input_value = 250
nearest = find_nearest_value(input_value, random_array)

print("Random Array:")
print(random_array)
print("Input Value:", input_value)
print("Nearest Value:", nearest)


# print("Array",array)
# print("Value",value)
# print("absolute_diff",absolute_diff)
# print("nearest_index",nearest_index)

Random Array:
[464 437 273 440  44 215  90 429  59 369 397  11 399  63 115]
Input Value: 250
Nearest Value: 273
